# Generated by Django 3.1.2 on 2020-10-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_custom_account_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
