# Generated by Django 3.1.2 on 2020-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_user_custom_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_custom_account_id',
            field=models.TextField(blank=True),
        ),
    ]
